
package adminservices;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdminService", targetNamespace = "http://admin/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdminService {


    /**
     * 
     * @return
     *     returns java.util.List<adminservices.Package>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPackages", targetNamespace = "http://admin/", className = "adminservices.GetAllPackages")
    @ResponseWrapper(localName = "getAllPackagesResponse", targetNamespace = "http://admin/", className = "adminservices.GetAllPackagesResponse")
    @Action(input = "http://admin/AdminService/getAllPackagesRequest", output = "http://admin/AdminService/getAllPackagesResponse")
    public List<Package> getAllPackages();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns adminservices.Package
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPackage", targetNamespace = "http://admin/", className = "adminservices.AddPackage")
    @ResponseWrapper(localName = "addPackageResponse", targetNamespace = "http://admin/", className = "adminservices.AddPackageResponse")
    @Action(input = "http://admin/AdminService/addPackageRequest", output = "http://admin/AdminService/addPackageResponse")
    public Package addPackage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removePackage", targetNamespace = "http://admin/", className = "adminservices.RemovePackage")
    @ResponseWrapper(localName = "removePackageResponse", targetNamespace = "http://admin/", className = "adminservices.RemovePackageResponse")
    @Action(input = "http://admin/AdminService/removePackageRequest", output = "http://admin/AdminService/removePackageResponse")
    public void removePackage(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns adminservices.Package
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerPackageForTracking", targetNamespace = "http://admin/", className = "adminservices.RegisterPackageForTracking")
    @ResponseWrapper(localName = "registerPackageForTrackingResponse", targetNamespace = "http://admin/", className = "adminservices.RegisterPackageForTrackingResponse")
    @Action(input = "http://admin/AdminService/registerPackageForTrackingRequest", output = "http://admin/AdminService/registerPackageForTrackingResponse")
    public Package registerPackageForTracking(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updatePackageStatus", targetNamespace = "http://admin/", className = "adminservices.UpdatePackageStatus")
    @ResponseWrapper(localName = "updatePackageStatusResponse", targetNamespace = "http://admin/", className = "adminservices.UpdatePackageStatusResponse")
    @Action(input = "http://admin/AdminService/updatePackageStatusRequest", output = "http://admin/AdminService/updatePackageStatusResponse")
    public void updatePackageStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns adminservices.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByUsernameAdmin", targetNamespace = "http://admin/", className = "adminservices.GetUserByUsernameAdmin")
    @ResponseWrapper(localName = "getUserByUsernameAdminResponse", targetNamespace = "http://admin/", className = "adminservices.GetUserByUsernameAdminResponse")
    @Action(input = "http://admin/AdminService/getUserByUsernameAdminRequest", output = "http://admin/AdminService/getUserByUsernameAdminResponse")
    public User getUserByUsernameAdmin(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
